# Generated by Django 3.2.4 on 2021-07-05 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=30)),
                ('nitems', models.IntegerField()),
                ('timings', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('rsimg', models.ImageField(default='logo.jpg', upload_to='Restaurantimages/')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='itemlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=30)),
                ('icategory', models.CharField(choices=[('NV', 'non-veg'), ('VG', 'veg')], default='Df', max_length=12)),
                ('iprice', models.IntegerField()),
                ('iimg', models.ImageField(default='logo.jpg', upload_to='Itemimages')),
                ('itavailability', models.CharField(choices=[('AV', 'Available'), ('NA', 'Not available'), ('s1', 'Select Availability')], default='s1', max_length=20)),
                ('rsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.restaurant')),
            ],
        ),
    ]
